[package]
name = "omni-vision"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
omni-core = { path = "../omni-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
image.workspace = true
magika = { version = "0.1", optional = true }
